resolver: nightly-2020-09-29
local-bin-path: ./bin
packages:
- .
nix:
  enable: true
  packages: [ zlib postgresql ]
extra-deps:
- servant-server-0.18
- postgresql-simple-migration-0.1.15.0
- base64-bytestring-1.0.0.3