name: "Build and deploy"

on:
  pull_request:
  push:

jobs:
  buid-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Nix
    - name: Cache ~/.stack, ~/.stack-work
      uses: actions/cache@v2
      with:
        path: |
          ~/.stack
          ~/.stack-work
      key: ${{ runner.os }}-${{ matrix.ghc }}
      uses: cachix/install-nix-action@v6
    - name: Install Stack
      run: $(nix-env -iA nixpkgs.stack)
    - name: Build project
      run: |
            mkdir -p bin
            stack install