name: "Build and deploy"

on:
  pull_request:
  push:

jobs:
  buid-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Nix
    - uses: actions/cache@v2
      with:
        path: |
          ~/.stack
          !~/.stack/setup-exe-cache
        key: ${{ runner.os }}-test-stack-${{ hashFiles('package.yaml') }}-${{ hashFiles('stack.yaml*') }}
      uses: cachix/install-nix-action@v6
    - name: Install Stack
      run: $(nix-env -iA nixpkgs.stack)
    - name: Build project
      run: |
            mkdir -p bin
            stack install